Dentosal/python-sc2

sc2/bot_ai.py
Adjusted automatic expansion detection to be more accurate and prevent town halls being placed next to each other.
A new `expand_now()` method has been added for convenience.
=> Reworked expansion

README.md
I thought it would be good to have a bit more detail on getting started with the project, specifically with downloading maps and running a bot.
I also fixed a couple spelling errors.
=> Update README.md with info on getting started

README.md, examples/terran/mass_reaper.py, sc2/client.py, sc2/data.py, sc2/game_data.py, sc2/game_info.py, sc2/game_state.py, sc2/helpers/control_group.py, sc2/position.py, sc2/score.py, sc2/unit.py, sc2/units.py
Add blips for sensor tower
Add comments to mass_reaper.py example
and more
=> Add score, mypy type checking and more

sc2/bot_ai.py, sc2/client.py
Fix an issue that would break older bots using abilities
=> Hotfix query_available_abilities

examples/terran/mass_reaper.py, sc2/bot_ai.py, sc2/client.py, sc2/game_data.py, sc2/game_info.py, sc2/game_state.py, sc2/unit.py, sc2/units.py
```markdown
- Zerg structure cost (everything that is built by a drone)
- Zerg structure morph (to lair, hive, greater spire)
- Command center morph (orbital command, planetary fortress)
- Unit morphs (zergling -> baneling, hydralisk -> lurker, corruptor -> broodlord) are still not fixed!
```
=> Fix cost of zerg structures and building morph cost

sc2/bot_ai.py, sc2/main.py
All credits for:
- [daniel-kukiela](https://github.com/daniel-kukiela/python-sc2/commit/615ad809306e6f6cd6410990c3c7228db5ffd900)
- [Sentdex](https://github.com/Sentdex)
=> Added 'on_end' method called at the end of a game with 'Result'

sc2/bot_ai.py
With short step time limits, doing all these actions one by one with
`do` is too slow. This attempt tries to fix it by building a single list
of actions and executing them all at once with `do_actions`.
=> Build a list of actions in distribute_workers

sc2/bot_ai.py, sc2/pixel_map.py, sc2/unit.py
Fix expansion locations for new maps (again)
Improve some code
Add scan_move ability
=> Get ready for sc2ai league season 7

README.md, sc2/paths.py
This makes the bots runnable on Linux with Wine.
=> Add WineLinux platform and SC2PF envvar to set the platform

sc2/controller.py, sc2/main.py
This will add a `random_seed` parameter to `run_game()` and pass it along to StarCraft2 to set the random number seed. Setting the random number seed allows for repeatable experiments.
=> Add random_seed parameter

sc2/bot_ai.py
It's useful to know if and when did the construction of a building begin. This commit adds a new `on_building_construction_started` event hook that bot developers can override to implement custom logic.
=> Adds 'on_building_construction_started' event hook to the bot.

sc2/game_data.py, sc2/game_state.py, sc2/unit.py
`unit.weapons` is currently bugged, here is the fix
=> Fix weapons in unit, improve game state init, cache typeid

sc2/action.py, sc2/bot_ai.py, sc2/cache.py, sc2/client.py, sc2/game_data.py, sc2/game_info.py, sc2/game_state.py, sc2/main.py, sc2/player.py, sc2/position.py, sc2/renderer.py, sc2/sc2process.py, sc2/score.py, sc2/unit.py, sc2/units.py
- Fix #212
- Remove unneccessary braces
- Improve `logging.info`
- Fix crash on sets in position
- Fix #216 
- Battlecruiser weapon workaround (BC does not have a weapon in proto)
- Add score summary
- Fix #217
=> Fix #212,  #216 and #217, little code improvements

sc2/main.py, sc2/portconfig.py, sc2/power_source.py, sc2/protocol.py, sc2/sc2process.py, sc2/unit.py, sc2/unit_command.py, sc2/units.py
- Add and update code comments
- Remove unused `.is_robotic`
- Add `is_carrying_resource`
- Add `buffs`
- Change unit order functions from `*args, **kwargs` arguments to `target, queue=False`
- Fix `take` in `units.py`
- Add `cargo_left` to `unit.py`
=> More comments for unit.py, add buffs, rewrite order functions

sc2/game_data.py
Implements `__add__` for `Cost` objects
=> Adding up Cost objects

sc2/main.py, sc2/player.py
Usage:
```py
run_game(maps.get("BlueshiftLE"), [
Human(Race.Zerg, fullscreen=True, name="Human"),
Bot(Race.Zerg, WorkerRushBot(), name="WorkerRush")],
realtime=True)
```
=> Add option for fullscreen windows

sc2/bot_ai.py
See https://github.com/Blizzard/s2client-proto/issues/123
=> Workaround for zerg supply rounding bug

sc2/bot_ai.py, sc2/client.py, sc2/game_state.py, sc2/position.py
- Speed up `action` with generator.
- Remove uneccessary condition in `game_state` unit loop
- Add `.is_further_than`
- Several type improvements
- Clean up comments
=> Speed up action and game_state, clean code

Pipfile, Pipfile.lock, sc2/pixel_map.py
At least 90% of credit to @BurnySc2 for the numpy implementation of the pixelmap object.
This increases the lookup speed in pixelmaps up to 50-70%.
=> Numpy implementation of the pixelmap object

sc2/bot_ai.py, sc2/main.py, sc2/unit.py, test/test_pickled_data.py
- Add note to `is_visible`
- Add `is_revealed`
- Add `attack/armor/shield upgrades`
- Add `buff timer`
- Add `terrain_to_z_height` function
- Fix `on_end` trigger at game end for ladder server games
- Fix proper temination at game end (ladder server does not need to wait any more)
=> Add more protocol updates
